version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Building...
      - yarn run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist